BEGIN;

SET search_path = public;

-- =============================================================================
-- DMIS LAST-MILE FOUNDATION (Production-safe, additive, idempotent)
-- -----------------------------------------------------------------------------
-- Your operational rules:
--  - MAIN-HUB (Haining Rd, Pimento, etc): donation intake allowed
--  - SUB-HUB (LSA under ODPEM): donation intake NOT allowed
--  - HSA (JDF, MLSS, Parish Councils): donation intake allowed into their own warehouses
--  - LSA can dispatch to ANY HSA warehouse (no static LSA→HSA assignment)
--  - Last-mile module: HSA warehouse → Beneficiary (Shelter & Individual)
-- -----------------------------------------------------------------------------
-- IMPORTANT: No drops / renames. All changes are additive.
-- =============================================================================


-- =============================================================================
-- 1) CLASSIFY CUSTODIANS AS LSA OR HSA (additive column)
--    - ODPEM custodian stays as LSA (but can still have MAIN and SUB hubs)
--    - HSA custodians (JDF/MLSS/etc.) will be set to HSA
-- =============================================================================

ALTER TABLE public.custodian
  ADD COLUMN IF NOT EXISTS org_type varchar(10);

-- Default any existing custodian rows to LSA if org_type is null
UPDATE public.custodian
   SET org_type = COALESCE(org_type, 'LSA')
 WHERE org_type IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_custodian_org_type') THEN
    ALTER TABLE public.custodian
      ADD CONSTRAINT c_custodian_org_type
      CHECK (org_type IN ('LSA','HSA'));
  END IF;
END$$;


-- =============================================================================
-- 2) HSA MASTER TABLE (in-scope only: JDF, MLSS, Parish Councils, etc.)
--    - Uses custodian as the authoritative organization record.
--    - 1:1 relationship: each HSA is a custodian with org_type='HSA'
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.hsa (
    hsa_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custodian_id  integer NOT NULL UNIQUE
      REFERENCES public.custodian(custodian_id) ON DELETE RESTRICT,

    hsa_code      varchar(30) NOT NULL UNIQUE,   -- e.g. JDF, MLSS, HSA_12 (for parish councils until refined)
    hsa_category  varchar(30) NOT NULL,          -- JDF, MLSS, PARISH_COUNCIL, OTHER
    status_code   char(1) NOT NULL DEFAULT 'A',
    notes         text,

    create_by_id  varchar(20) NOT NULL DEFAULT 'SYSTEM',
    create_dtime  timestamp(0) without time zone NOT NULL DEFAULT now(),
    update_by_id  varchar(20) NOT NULL DEFAULT 'SYSTEM',
    update_dtime  timestamp(0) without time zone NOT NULL DEFAULT now(),
    version_nbr   integer NOT NULL DEFAULT 1
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_hsa_code_upper') THEN
    ALTER TABLE public.hsa
      ADD CONSTRAINT c_hsa_code_upper CHECK (hsa_code = upper(hsa_code));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_hsa_category') THEN
    ALTER TABLE public.hsa
      ADD CONSTRAINT c_hsa_category CHECK (hsa_category IN ('JDF','MLSS','PARISH_COUNCIL','OTHER'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_hsa_status') THEN
    ALTER TABLE public.hsa
      ADD CONSTRAINT c_hsa_status CHECK (status_code IN ('A','I'));
  END IF;
END$$;

-- Helpful index for ownership lookups (HSA can have many warehouses via warehouse.custodian_id)
CREATE INDEX IF NOT EXISTS ix_warehouse_custodian ON public.warehouse(custodian_id);


-- =============================================================================
-- 2A) OPTIONAL SAFE SEEDING (non-breaking)
--    If custodians already exist for JDF/MLSS/Parish Councils, we can classify them.
--    This is "best effort": it only affects matching names and is safe to override later.
-- =============================================================================

-- Seed MLSS if present
INSERT INTO public.hsa (custodian_id, hsa_code, hsa_category, status_code, notes)
SELECT c.custodian_id, 'MLSS', 'MLSS', 'A', 'Seeded from custodian_name match'
FROM public.custodian c
WHERE c.custodian_name ILIKE '%MLSS%'
  AND NOT EXISTS (SELECT 1 FROM public.hsa h WHERE h.custodian_id = c.custodian_id);

-- Seed JDF if present
INSERT INTO public.hsa (custodian_id, hsa_code, hsa_category, status_code, notes)
SELECT c.custodian_id, 'JDF', 'JDF', 'A', 'Seeded from custodian_name match'
FROM public.custodian c
WHERE c.custodian_name ILIKE '%JDF%'
  AND NOT EXISTS (SELECT 1 FROM public.hsa h WHERE h.custodian_id = c.custodian_id);

-- Seed Parish Councils if present (unique code per custodian: HSA_<custodian_id>)
INSERT INTO public.hsa (custodian_id, hsa_code, hsa_category, status_code, notes)
SELECT c.custodian_id, ('HSA_' || c.custodian_id::text), 'PARISH_COUNCIL', 'A',
       'Seeded from custodian_name match; rename hsa_code later to parish-specific code'
FROM public.custodian c
WHERE c.custodian_name ILIKE '%PARISH%'
  AND c.custodian_name ILIKE '%COUNCIL%'
  AND NOT EXISTS (SELECT 1 FROM public.hsa h WHERE h.custodian_id = c.custodian_id);

-- Ensure custodians linked to HSA are marked org_type='HSA'
UPDATE public.custodian c
SET org_type = 'HSA'
WHERE EXISTS (SELECT 1 FROM public.hsa h WHERE h.custodian_id = c.custodian_id);


-- =============================================================================
-- 3) WAREHOUSE TIERING + DONATION INTAKE RULES (additive columns)
--    - MAIN-HUB = tier MAIN (ODPEM main hubs)
--    - SUB-HUB  = tier LSA  (ODPEM sub-hubs / LSA)
--    - Any warehouse owned by an HSA custodian = tier HSA
--    - Donation intake allowed for MAIN and HSA, not allowed for LSA
-- =============================================================================

ALTER TABLE public.warehouse
  ADD COLUMN IF NOT EXISTS warehouse_tier varchar(10);

ALTER TABLE public.warehouse
  ADD COLUMN IF NOT EXISTS allows_donation_intake boolean;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_warehouse_tier') THEN
    ALTER TABLE public.warehouse
      ADD CONSTRAINT c_warehouse_tier
      CHECK (warehouse_tier IS NULL OR warehouse_tier IN ('MAIN','LSA','HSA'));
  END IF;
END$$;

-- Owner-first tier assignment:
--  (1) If custodian is HSA -> warehouse tier = HSA
UPDATE public.warehouse w
SET warehouse_tier = 'HSA'
FROM public.custodian c
WHERE w.custodian_id = c.custodian_id
  AND c.org_type = 'HSA'
  AND (w.warehouse_tier IS NULL OR w.warehouse_tier <> 'HSA');

--  (2) Otherwise use warehouse_type mapping (ODPEM MAIN/SUB hubs)
UPDATE public.warehouse
SET warehouse_tier = CASE
  WHEN warehouse_type = 'MAIN-HUB' THEN 'MAIN'
  WHEN warehouse_type = 'SUB-HUB'  THEN 'LSA'
  ELSE warehouse_tier
END
WHERE warehouse_tier IS NULL
  AND warehouse_type IN ('MAIN-HUB','SUB-HUB');

-- Donation intake rule derived from tier (non-breaking; nullable allowed)
UPDATE public.warehouse
SET allows_donation_intake = CASE
  WHEN warehouse_tier IN ('MAIN','HSA') THEN TRUE
  WHEN warehouse_tier = 'LSA' THEN FALSE
  ELSE allows_donation_intake
END
WHERE allows_donation_intake IS NULL
  AND warehouse_tier IS NOT NULL;

-- Optional view for UI filters (safe)
CREATE OR REPLACE VIEW public.v_warehouse_intake_eligible AS
SELECT w.*
FROM public.warehouse w
WHERE w.status_code = 'A'
  AND w.allows_donation_intake = TRUE;


-- =============================================================================
-- 4) BENEFICIARY MASTER TABLE (single table: INDIVIDUAL or SHELTER)
--    - Individuals are created during HSA distribution workflow (registered_hsa_id)
--    - Shelters can be mapped from legacy agency(SHELTER) for smooth transition
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.beneficiary (
    beneficiary_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    beneficiary_type    varchar(12) NOT NULL,     -- INDIVIDUAL | SHELTER

    -- Display name used everywhere:
    --  - SHELTER: shelter name
    --  - INDIVIDUAL: full name (or "given + family")
    beneficiary_name    varchar(160) NOT NULL,

    -- Structured fields (primarily INDIVIDUAL)
    given_name          varchar(80),
    family_name         varchar(80),

    phone_no            varchar(20),
    email_text          varchar(100),

    parish_code         char(2),
    community_text      varchar(120),
    address1_text       varchar(255),
    address2_text       varchar(255),

    -- Captured by which HSA (important for last-mile workflow + visibility)
    registered_hsa_id   integer
      REFERENCES public.hsa(hsa_id) ON DELETE SET NULL,

    -- Transitional link to existing shelter agency (do NOT remove agency yet)
    shelter_agency_id   integer UNIQUE
      REFERENCES public.agency(agency_id) ON DELETE SET NULL,

    status_code         char(1) NOT NULL DEFAULT 'A',
    notes               text,

    create_by_id        varchar(20) NOT NULL DEFAULT 'SYSTEM',
    create_dtime        timestamp(0) without time zone NOT NULL DEFAULT now(),
    update_by_id        varchar(20) NOT NULL DEFAULT 'SYSTEM',
    update_dtime        timestamp(0) without time zone NOT NULL DEFAULT now(),
    version_nbr         integer NOT NULL DEFAULT 1
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_beneficiary_type') THEN
    ALTER TABLE public.beneficiary
      ADD CONSTRAINT c_beneficiary_type
      CHECK (beneficiary_type IN ('INDIVIDUAL','SHELTER'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_beneficiary_status') THEN
    ALTER TABLE public.beneficiary
      ADD CONSTRAINT c_beneficiary_status CHECK (status_code IN ('A','I'));
  END IF;

  -- Type-specific requirement:
  --  - INDIVIDUAL must have given_name and family_name
  --  - SHELTER must NOT have given_name/family_name
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_beneficiary_required_fields') THEN
    ALTER TABLE public.beneficiary
      ADD CONSTRAINT c_beneficiary_required_fields CHECK (
        (beneficiary_type = 'INDIVIDUAL' AND given_name IS NOT NULL AND family_name IS NOT NULL)
        OR
        (beneficiary_type = 'SHELTER' AND given_name IS NULL AND family_name IS NULL)
      );
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS ix_beneficiary_type ON public.beneficiary(beneficiary_type);
CREATE INDEX IF NOT EXISTS ix_beneficiary_registered_hsa ON public.beneficiary(registered_hsa_id);

-- Optional compatibility migration: load existing shelters from agency into beneficiary
INSERT INTO public.beneficiary (
  beneficiary_type,
  beneficiary_name,
  parish_code,
  address1_text,
  address2_text,
  phone_no,
  email_text,
  shelter_agency_id,
  status_code,
  create_by_id,
  create_dtime,
  update_by_id,
  update_dtime,
  version_nbr
)
SELECT
  'SHELTER',
  a.agency_name,
  a.parish_code,
  a.address1_text,
  a.address2_text,
  a.phone_no,
  a.email_text,
  a.agency_id,
  a.status_code,
  a.create_by_id,
  a.create_dtime,
  a.update_by_id,
  a.update_dtime,
  a.version_nbr
FROM public.agency a
WHERE a.agency_type = 'SHELTER'
  AND NOT EXISTS (
    SELECT 1 FROM public.beneficiary b
    WHERE b.shelter_agency_id = a.agency_id
  );

-- Convenience view for UI
CREATE OR REPLACE VIEW public.v_beneficiary_display AS
SELECT
  b.beneficiary_id,
  b.beneficiary_type,
  b.beneficiary_name AS display_name,
  b.phone_no,
  b.parish_code,
  b.community_text,
  b.status_code,
  b.registered_hsa_id,
  b.shelter_agency_id
FROM public.beneficiary b;


-- =============================================================================
-- 5) LAST-MILE MODULE TABLES (HSA warehouse -> beneficiary)
--    These are new and do NOT interfere with existing distribution_package flows.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.lastmile_distribution (
    distribution_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    hsa_id              integer NOT NULL
      REFERENCES public.hsa(hsa_id) ON DELETE RESTRICT,

    warehouse_id        integer NOT NULL
      REFERENCES public.warehouse(warehouse_id) ON DELETE RESTRICT,

    beneficiary_id      integer NOT NULL
      REFERENCES public.beneficiary(beneficiary_id) ON DELETE RESTRICT,

    event_id            integer
      REFERENCES public.event(event_id) ON DELETE SET NULL,

    distribution_dtime  timestamp(0) without time zone NOT NULL DEFAULT now(),
    status_code         char(1) NOT NULL DEFAULT 'D',     -- D Draft | C Completed | V Verified | X Cancelled
    notes               text,

    create_by_id        varchar(20) NOT NULL DEFAULT 'SYSTEM',
    create_dtime        timestamp(0) without time zone NOT NULL DEFAULT now(),
    update_by_id        varchar(20) NOT NULL DEFAULT 'SYSTEM',
    update_dtime        timestamp(0) without time zone NOT NULL DEFAULT now(),

    verify_by_id        varchar(20),
    verify_dtime        timestamp(0) without time zone,

    version_nbr         integer NOT NULL DEFAULT 1
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_lastmile_dist_status') THEN
    ALTER TABLE public.lastmile_distribution
      ADD CONSTRAINT c_lastmile_dist_status CHECK (status_code IN ('D','C','V','X'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_lastmile_dist_verify_pair') THEN
    ALTER TABLE public.lastmile_distribution
      ADD CONSTRAINT c_lastmile_dist_verify_pair
      CHECK (
        (verify_by_id IS NULL AND verify_dtime IS NULL)
        OR
        (verify_by_id IS NOT NULL AND verify_dtime IS NOT NULL)
      );
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS ix_lastmile_dist_hsa_date
  ON public.lastmile_distribution(hsa_id, distribution_dtime);

CREATE INDEX IF NOT EXISTS ix_lastmile_dist_beneficiary
  ON public.lastmile_distribution(beneficiary_id);

CREATE INDEX IF NOT EXISTS ix_lastmile_dist_warehouse
  ON public.lastmile_distribution(warehouse_id);


CREATE TABLE IF NOT EXISTS public.lastmile_distribution_item (
    distribution_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    distribution_id      integer NOT NULL
      REFERENCES public.lastmile_distribution(distribution_id) ON DELETE CASCADE,

    item_id              integer NOT NULL
      REFERENCES public.item(item_id) ON DELETE RESTRICT,

    batch_id             integer
      REFERENCES public.itembatch(batch_id) ON DELETE SET NULL,

    uom_code             character varying(25)
      REFERENCES public.unitofmeasure(uom_code) ON DELETE RESTRICT,

    qty                  numeric(12,2) NOT NULL,
    notes                text
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_lastmile_dist_item_qty') THEN
    ALTER TABLE public.lastmile_distribution_item
      ADD CONSTRAINT c_lastmile_dist_item_qty CHECK (qty > 0);
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS ix_lastmile_item_dist
  ON public.lastmile_distribution_item(distribution_id);

CREATE INDEX IF NOT EXISTS ix_lastmile_item_item
  ON public.lastmile_distribution_item(item_id);

CREATE INDEX IF NOT EXISTS ix_lastmile_item_batch
  ON public.lastmile_distribution_item(batch_id);


-- Optional: receipt/proof-of-receipt (safe, can be used later)
CREATE TABLE IF NOT EXISTS public.lastmile_distribution_receipt (
    receipt_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_id   integer NOT NULL UNIQUE
      REFERENCES public.lastmile_distribution(distribution_id) ON DELETE CASCADE,

    received_by_name  varchar(120),
    received_by_phone varchar(20),
    received_dtime    timestamp(0) without time zone DEFAULT now(),

    signature_type    varchar(12),     -- TYPED | DRAWN | UPLOAD
    signature_text    text,            -- for typed
    signature_path    text,            -- for file storage path (if upload)
    signature_hash    varchar(128),    -- optional integrity hash
    notes             text
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'c_lastmile_receipt_sigtype') THEN
    ALTER TABLE public.lastmile_distribution_receipt
      ADD CONSTRAINT c_lastmile_receipt_sigtype
      CHECK (signature_type IS NULL OR signature_type IN ('TYPED','DRAWN','UPLOAD'));
  END IF;
END$$;

-- Optional: supporting docs
CREATE TABLE IF NOT EXISTS public.lastmile_distribution_doc (
    doc_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribution_id  integer NOT NULL
      REFERENCES public.lastmile_distribution(distribution_id) ON DELETE CASCADE,

    doc_type         varchar(30),
    file_name        varchar(255),
    file_path        text,
    file_hash        varchar(128),

    create_by_id     varchar(20) NOT NULL DEFAULT 'SYSTEM',
    create_dtime     timestamp(0) without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_lastmile_doc_dist
  ON public.lastmile_distribution_doc(distribution_id);


-- =============================================================================
-- 6) EXTEND public.transaction FOR TRACEABILITY (optional, non-breaking)
--    - keep existing columns untouched
--    - add optional linkage fields for last-mile documents and beneficiary
-- =============================================================================

ALTER TABLE public.transaction
  ADD COLUMN IF NOT EXISTS source_doc_type varchar(30),
  ADD COLUMN IF NOT EXISTS source_doc_id integer,
  ADD COLUMN IF NOT EXISTS hsa_id integer,
  ADD COLUMN IF NOT EXISTS beneficiary_id integer,
  ADD COLUMN IF NOT EXISTS batch_id integer,
  ADD COLUMN IF NOT EXISTS uom_code varchar(25);

CREATE INDEX IF NOT EXISTS ix_tx_source_doc ON public.transaction(source_doc_type, source_doc_id);
CREATE INDEX IF NOT EXISTS ix_tx_beneficiary ON public.transaction(beneficiary_id);
CREATE INDEX IF NOT EXISTS ix_tx_hsa ON public.transaction(hsa_id);
CREATE INDEX IF NOT EXISTS ix_tx_batch ON public.transaction(batch_id);


-- =============================================================================
-- 7) VIEWS FOR REPORTING + UI FILTERS (safe)
-- =============================================================================

-- All warehouses belonging to HSAs (HSA can have many warehouses via custodian_id)
CREATE OR REPLACE VIEW public.v_hsa_warehouses AS
SELECT
  h.hsa_id,
  h.hsa_code,
  h.hsa_category,
  c.custodian_id,
  c.custodian_name,
  w.warehouse_id,
  w.warehouse_name,
  w.warehouse_type,
  w.warehouse_tier,
  w.allows_donation_intake,
  w.parish_code,
  w.status_code
FROM public.hsa h
JOIN public.custodian c ON c.custodian_id = h.custodian_id
JOIN public.warehouse  w ON w.custodian_id = c.custodian_id;

COMMIT;
